// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/common/v1/common.proto

package io.opentelemetry.proto.common.v1;

/**
 * <pre>
 * StringKeyValue is a pair of key/value strings. This is the simpler (and faster) version
 * of KeyValue that only supports string values.
 * </pre>
 * <p>
 * Protobuf type {@code opentelemetry.proto.common.v1.StringKeyValue}
 */
@Deprecated
public final class StringKeyValue extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:opentelemetry.proto.common.v1.StringKeyValue)
        StringKeyValueOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use StringKeyValue.newBuilder() to construct.
    private StringKeyValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private StringKeyValue() {
        key_ = "";
        value_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new StringKeyValue();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private StringKeyValue(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        String s = input.readStringRequireUtf8();

                        key_ = s;
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        value_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return CommonProto.internal_static_opentelemetry_proto_common_v1_StringKeyValue_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return CommonProto.internal_static_opentelemetry_proto_common_v1_StringKeyValue_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        StringKeyValue.class, Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile Object key_;

    /**
     * <code>string key = 1;</code>
     *
     * @return The key.
     */
    @Override
    public String getKey() {
        Object ref = key_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            key_ = s;
            return s;
        }
    }

    /**
     * <code>string key = 1;</code>
     *
     * @return The bytes for key.
     */
    @Override
    public com.google.protobuf.ByteString
    getKeyBytes() {
        Object ref = key_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            key_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile Object value_;

    /**
     * <code>string value = 2;</code>
     *
     * @return The value.
     */
    @Override
    public String getValue() {
        Object ref = value_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            value_ = s;
            return s;
        }
    }

    /**
     * <code>string value = 2;</code>
     *
     * @return The bytes for value.
     */
    @Override
    public com.google.protobuf.ByteString
    getValueBytes() {
        Object ref = value_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            value_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getKeyBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
        }
        if (!getValueBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getKeyBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
        }
        if (!getValueBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof StringKeyValue)) {
            return super.equals(obj);
        }
        StringKeyValue other = (StringKeyValue) obj;

        if (!getKey()
                .equals(other.getKey())) return false;
        if (!getValue()
                .equals(other.getValue())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static StringKeyValue parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static StringKeyValue parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static StringKeyValue parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static StringKeyValue parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static StringKeyValue parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static StringKeyValue parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static StringKeyValue parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static StringKeyValue parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static StringKeyValue parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static StringKeyValue parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static StringKeyValue parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static StringKeyValue parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(StringKeyValue prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * StringKeyValue is a pair of key/value strings. This is the simpler (and faster) version
     * of KeyValue that only supports string values.
     * </pre>
     * <p>
     * Protobuf type {@code opentelemetry.proto.common.v1.StringKeyValue}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:opentelemetry.proto.common.v1.StringKeyValue)
            StringKeyValueOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return CommonProto.internal_static_opentelemetry_proto_common_v1_StringKeyValue_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return CommonProto.internal_static_opentelemetry_proto_common_v1_StringKeyValue_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            StringKeyValue.class, Builder.class);
        }

        // Construct using io.opentelemetry.proto.common.v1.StringKeyValue.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            key_ = "";

            value_ = "";

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return CommonProto.internal_static_opentelemetry_proto_common_v1_StringKeyValue_descriptor;
        }

        @Override
        public StringKeyValue getDefaultInstanceForType() {
            return StringKeyValue.getDefaultInstance();
        }

        @Override
        public StringKeyValue build() {
            StringKeyValue result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public StringKeyValue buildPartial() {
            StringKeyValue result = new StringKeyValue(this);
            result.key_ = key_;
            result.value_ = value_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof StringKeyValue) {
                return mergeFrom((StringKeyValue) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(StringKeyValue other) {
            if (other == StringKeyValue.getDefaultInstance()) return this;
            if (!other.getKey().isEmpty()) {
                key_ = other.key_;
                onChanged();
            }
            if (!other.getValue().isEmpty()) {
                value_ = other.value_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            StringKeyValue parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (StringKeyValue) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private Object key_ = "";

        /**
         * <code>string key = 1;</code>
         *
         * @return The key.
         */
        public String getKey() {
            Object ref = key_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                key_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string key = 1;</code>
         *
         * @return The bytes for key.
         */
        public com.google.protobuf.ByteString
        getKeyBytes() {
            Object ref = key_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                key_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string key = 1;</code>
         *
         * @param value The key to set.
         * @return This builder for chaining.
         */
        public Builder setKey(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            key_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string key = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearKey() {

            key_ = getDefaultInstance().getKey();
            onChanged();
            return this;
        }

        /**
         * <code>string key = 1;</code>
         *
         * @param value The bytes for key to set.
         * @return This builder for chaining.
         */
        public Builder setKeyBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            key_ = value;
            onChanged();
            return this;
        }

        private Object value_ = "";

        /**
         * <code>string value = 2;</code>
         *
         * @return The value.
         */
        public String getValue() {
            Object ref = value_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                value_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string value = 2;</code>
         *
         * @return The bytes for value.
         */
        public com.google.protobuf.ByteString
        getValueBytes() {
            Object ref = value_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                value_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string value = 2;</code>
         *
         * @param value The value to set.
         * @return This builder for chaining.
         */
        public Builder setValue(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            value_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string value = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearValue() {

            value_ = getDefaultInstance().getValue();
            onChanged();
            return this;
        }

        /**
         * <code>string value = 2;</code>
         *
         * @param value The bytes for value to set.
         * @return This builder for chaining.
         */
        public Builder setValueBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            value_ = value;
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:opentelemetry.proto.common.v1.StringKeyValue)
    }

    // @@protoc_insertion_point(class_scope:opentelemetry.proto.common.v1.StringKeyValue)
    private static final StringKeyValue DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new StringKeyValue();
    }

    public static StringKeyValue getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StringKeyValue>
            PARSER = new com.google.protobuf.AbstractParser<StringKeyValue>() {
        @Override
        public StringKeyValue parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new StringKeyValue(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<StringKeyValue> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<StringKeyValue> getParserForType() {
        return PARSER;
    }

    @Override
    public StringKeyValue getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

