// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/common/v1/common.proto

package io.opentelemetry.proto.common.v1;

@Deprecated
public interface StringKeyValueOrBuilder extends
        // @@protoc_insertion_point(interface_extends:opentelemetry.proto.common.v1.StringKeyValue)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     *
     * @return The key.
     */
    String getKey();

    /**
     * <code>string key = 1;</code>
     *
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
    getKeyBytes();

    /**
     * <code>string value = 2;</code>
     *
     * @return The value.
     */
    String getValue();

    /**
     * <code>string value = 2;</code>
     *
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
    getValueBytes();
}
