// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/metrics/v1/metrics.proto

package io.opentelemetry.proto.metrics.v1;

@Deprecated
public interface IntHistogramOrBuilder extends
        // @@protoc_insertion_point(interface_extends:opentelemetry.proto.metrics.v1.IntHistogram)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .opentelemetry.proto.metrics.v1.IntHistogramDataPoint data_points = 1;</code>
     */
    java.util.List<IntHistogramDataPoint>
    getDataPointsList();

    /**
     * <code>repeated .opentelemetry.proto.metrics.v1.IntHistogramDataPoint data_points = 1;</code>
     */
    IntHistogramDataPoint getDataPoints(int index);

    /**
     * <code>repeated .opentelemetry.proto.metrics.v1.IntHistogramDataPoint data_points = 1;</code>
     */
    int getDataPointsCount();

    /**
     * <code>repeated .opentelemetry.proto.metrics.v1.IntHistogramDataPoint data_points = 1;</code>
     */
    java.util.List<? extends IntHistogramDataPointOrBuilder>
    getDataPointsOrBuilderList();

    /**
     * <code>repeated .opentelemetry.proto.metrics.v1.IntHistogramDataPoint data_points = 1;</code>
     */
    IntHistogramDataPointOrBuilder getDataPointsOrBuilder(
            int index);

    /**
     * <pre>
     * aggregation_temporality describes if the aggregator reports delta changes
     * since last report time, or cumulative changes since a fixed start time.
     * </pre>
     *
     * <code>.opentelemetry.proto.metrics.v1.AggregationTemporality aggregation_temporality = 2;</code>
     *
     * @return The enum numeric value on the wire for aggregationTemporality.
     */
    int getAggregationTemporalityValue();

    /**
     * <pre>
     * aggregation_temporality describes if the aggregator reports delta changes
     * since last report time, or cumulative changes since a fixed start time.
     * </pre>
     *
     * <code>.opentelemetry.proto.metrics.v1.AggregationTemporality aggregation_temporality = 2;</code>
     *
     * @return The aggregationTemporality.
     */
    AggregationTemporality getAggregationTemporality();
}
